# Generated by Django 3.1.5 on 2021-01-12 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.CharField(max_length=255)),
                ('kanji', models.CharField(max_length=255)),
                ('kunyomi', models.CharField(blank=True, max_length=255, null=True)),
                ('onyomi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('word', models.CharField(max_length=255)),
                ('mean', models.CharField(max_length=255)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kanji')),
            ],
        ),
    ]
