# Generated by Django 3.1.5 on 2021-01-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='kanji',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(upload_to='upload\\word'),
        ),
    ]
